/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_rap;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.MenuElement;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 *
 * @author NguyenLinh
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    
    public frmMain() {
        initComponents();   
        KhoiDong();
    }
    
    public void KhoiDong() {
        if (MySqlConnect.quyen.equals("admin")) {
            phanquyen(false);
            jmnDangNhap.setVisible(false);
        } 
        if (MySqlConnect.quyen.equals("user")) {
            phanquyen(true);
            jmnDangNhap.setVisible(false);
        }
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/icon_QLDSV.png")));
        this.setLocationRelativeTo(null);
        customizeMenuBar(jMenuBar1);
        Color color = new Color(3, 31, 70);
        jPanel2.setBackground(color);
        Color mycolor = new Color(1, 6, 10);
        jPanel9.setBackground(mycolor );
        lblBg.setSize(600,150);
        scaleImageLabel("../images/tangchu.jpg", lblBg);
        lblUser.setText("User: " +MySqlConnect.userID);
        lblDate.setText("Today: "+getDt());
    }
    
    public void phanquyen(boolean value)
    {
        jmenuQLRap.setVisible(!value);
        jmnuQLNV.setVisible(!value);
        jmenuPhim.setVisible(value);
        jmenuBanVe.setVisible(value);
    }
    
    public static String getDt(){
        Date thoiGian = new Date();         
        SimpleDateFormat dinhDangThoiGian = new SimpleDateFormat("dd/MM/yyyy ");   
        String showTime = dinhDangThoiGian.format(thoiGian.getTime());
        return showTime;
    }
    
    public void centerJIF(JInternalFrame jif) {
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }
    
    public void scaleImageLabel(String imgPath, JLabel lbl)
    {
        ImageIcon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource(imgPath)));
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        lbl.setIcon(scaleIcon);
    }
    
    private void customizeMenuBar(JMenuBar menuBar) {
        menuBar.setUI(new BasicMenuBarUI() {
            public void paint(Graphics g, JComponent c) {
                Color mycolor = new Color(131, 37, 83);
                g.setColor(mycolor);
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }
        });
        MenuElement[] menus = menuBar.getSubElements();
        for (MenuElement menuElement : menus) {
            JMenu menu = (JMenu) menuElement.getComponent();
            changeComponentColors(menu);
            menu.setOpaque(false);
            MenuElement[] menuElements = menu.getSubElements();
            for (MenuElement popupMenuElement : menuElements) {
                JPopupMenu popupMenu = (JPopupMenu) popupMenuElement.getComponent();
                popupMenu.setBorder(null);
                MenuElement[] menuItens = popupMenuElement.getSubElements();
                for (MenuElement menuItemElement : menuItens) {
                    JMenuItem menuItem = (JMenuItem) menuItemElement.getComponent();
                    changeComponentColors(menuItem);
                    menuItem.setOpaque(true);
                }
            }
        }
    }
    private void changeComponentColors(Component comp) {
        Color myColor = new Color(246, 71, 71);
        comp.setBackground(myColor);
        comp.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpnTroGiup = new javax.swing.JPanel();
        lblTrogiup = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jpnThongTin = new javax.swing.JPanel();
        lblThongTin = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblBg = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnSinhVien = new javax.swing.JMenu();
        jmnDangNhap = new javax.swing.JMenuItem();
        jmnuQLNV = new javax.swing.JMenuItem();
        jmnGiangVien = new javax.swing.JMenu();
        jmenuPhim = new javax.swing.JMenuItem();
        jmenuQLRap = new javax.swing.JMenuItem();
        jmenuBanVe = new javax.swing.JMenuItem();
        jmnDangXuat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhân viên");
        setBackground(new java.awt.Color(255, 255, 255));

        jpnRoot.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        lblUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu1_white_24dp.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );

        jpnTroGiup.setBackground(new java.awt.Color(76, 175, 80));
        jpnTroGiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnTroGiupMouseClicked(evt);
            }
        });

        lblTrogiup.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTrogiup.setForeground(new java.awt.Color(255, 255, 255));
        lblTrogiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_help_white_24dp.png"))); // NOI18N
        lblTrogiup.setText("Hướng dẫn");
        lblTrogiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrogiupMouseClicked(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 0, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnTroGiupLayout = new javax.swing.GroupLayout(jpnTroGiup);
        jpnTroGiup.setLayout(jpnTroGiupLayout);
        jpnTroGiupLayout.setHorizontalGroup(
            jpnTroGiupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTroGiupLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTrogiup, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTroGiupLayout.setVerticalGroup(
            jpnTroGiupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTroGiupLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpnTroGiupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTrogiup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jpnThongTin.setBackground(new java.awt.Color(76, 175, 80));
        jpnThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnThongTinMouseClicked(evt);
            }
        });

        lblThongTin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblThongTin.setForeground(new java.awt.Color(255, 255, 255));
        lblThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_info_white_24dp.png"))); // NOI18N
        lblThongTin.setText("Thông tin phầm mềm");
        lblThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongTinMouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 0, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnThongTinLayout = new javax.swing.GroupLayout(jpnThongTin);
        jpnThongTin.setLayout(jpnThongTinLayout);
        jpnThongTinLayout.setHorizontalGroup(
            jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jpnThongTinLayout.setVerticalGroup(
            jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpnThongTin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnTroGiup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jpnTroGiup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jpnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 532, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        lblBg.setBackground(new java.awt.Color(255, 153, 153));
        lblBg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lblBg, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBg, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1)))
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        jmnSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_sv.png"))); // NOI18N
        jmnSinhVien.setText("Người dùng");
        jmnSinhVien.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jmnDangNhap.setText("Đăng nhập");
        jmnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnDangNhapActionPerformed(evt);
            }
        });
        jmnSinhVien.add(jmnDangNhap);

        jmnuQLNV.setText("Quản lý nhân viên");
        jmnuQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuQLNVActionPerformed(evt);
            }
        });
        jmnSinhVien.add(jmnuQLNV);

        jMenuBar1.add(jmnSinhVien);

        jmnGiangVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_teacher.png"))); // NOI18N
        jmnGiangVien.setText("Rạp phim");
        jmnGiangVien.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jmenuPhim.setText("Phim");
        jmenuPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuPhimActionPerformed(evt);
            }
        });
        jmnGiangVien.add(jmenuPhim);

        jmenuQLRap.setText("Quản lý rạp");
        jmenuQLRap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuQLRapActionPerformed(evt);
            }
        });
        jmnGiangVien.add(jmenuQLRap);

        jmenuBanVe.setText("Bán vé");
        jmnGiangVien.add(jmenuBanVe);

        jMenuBar1.add(jmnGiangVien);

        jmnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_logout.png"))); // NOI18N
        jmnDangXuat.setText("Đăng xuất");
        jmnDangXuat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jmnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnDangXuatMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmnDangXuat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void setBackg(){
        jpnThongTin.setBackground(new Color(76,175,80));
        jpnTroGiup.setBackground(new Color(76,175,80));
    }
    private void jpnTroGiupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnTroGiupMouseClicked
        frmHuongDan hd = new frmHuongDan();
        hd.setVisible(true);
        setBackg();
        jpnTroGiup.setBackground(new Color(96, 100, 191));
    }//GEN-LAST:event_jpnTroGiupMouseClicked

    private void lblTrogiupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrogiupMouseClicked
        frmHuongDan hd = new frmHuongDan();
        hd.setVisible(true);
        setBackg();
        jpnTroGiup.setBackground(new Color(96, 100, 191));
    }//GEN-LAST:event_lblTrogiupMouseClicked

    private void lblThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongTinMouseClicked
        setBackg();
        jpnThongTin.setBackground(new Color(96, 100, 191));
        JOptionPane.showMessageDialog(this, "<html><body><p style='width: 150px;'><b>Name: </b> Quản lý Nhân Viên <br/><b>Version: </b>1.0<br/><b>Desiger: </b>Nguyễn Lê Hải<br/> </p></body></html>", "Thông tin phần mềm", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblThongTinMouseClicked

    private void jpnThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnThongTinMouseClicked
        setBackg();
        jpnThongTin.setBackground(new Color(96, 100, 191));
        JOptionPane.showMessageDialog(this, "<html><body><p style='width: 150px;'><b>Name: </b> Quản lý Nhân Viên <br/><b>Version: </b>1.0<br/><b>Desiger: </b>Nguyễn Lê Hải<br/> </p></body></html>", "Thông tin phần mềm", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jpnThongTinMouseClicked

    private void jmnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnDangXuatMouseClicked
        MySqlConnect.userID = "";
        MySqlConnect.name = "";
        MySqlConnect.pass= "";
        MySqlConnect.quyen = "";
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmnDangXuatMouseClicked

    private void jmnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnDangNhapActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        setBackg();
        jpnTroGiup.setBackground(new Color(96, 100, 191));
    }//GEN-LAST:event_jmnDangNhapActionPerformed

    private void jmnuQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuQLNVActionPerformed
        setBackg();
          if(jDesktopPane1!=null)
          {
            jDesktopPane1.removeAll();
            jDesktopPane1.updateUI();
          }
          NhanVien nv = new NhanVien();
          jDesktopPane1.add(nv).setVisible(true);
          centerJIF(nv);
    }//GEN-LAST:event_jmnuQLNVActionPerformed

    private void jmenuPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuPhimActionPerformed
        setBackg();
          if(jDesktopPane1!=null)
          {
            jDesktopPane1.removeAll();
            jDesktopPane1.updateUI();
          }
          Phim phim = new Phim();
          jDesktopPane1.add(phim).setVisible(true);
          centerJIF(phim);
    }//GEN-LAST:event_jmenuPhimActionPerformed

    private void jmenuQLRapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuQLRapActionPerformed
        setBackg();
          if(jDesktopPane1!=null)
          {
            jDesktopPane1.removeAll();
            jDesktopPane1.updateUI();
          }
          Rap rap = new Rap();
          jDesktopPane1.add(rap).setVisible(true);
          centerJIF(rap);
    }//GEN-LAST:event_jmenuQLRapActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JMenuItem jmenuBanVe;
    private javax.swing.JMenuItem jmenuPhim;
    private javax.swing.JMenuItem jmenuQLRap;
    private javax.swing.JMenuItem jmnDangNhap;
    private javax.swing.JMenu jmnDangXuat;
    private javax.swing.JMenu jmnGiangVien;
    private javax.swing.JMenu jmnSinhVien;
    private javax.swing.JMenuItem jmnuQLNV;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnThongTin;
    private javax.swing.JPanel jpnTroGiup;
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblThongTin;
    private javax.swing.JLabel lblTrogiup;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
